apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres.yaml
  - awx.yaml
  - ingress.yaml
  - awx-admin-sealedsecrets.yaml
  - awx-secret-key-sealedsecrets.yaml
  - awx-postgres-config-sealedsecrets.yaml
  - certificate-awx.yaml