apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - sealedsecret-admin.yaml
  - sealedsecret-secretkey.yaml
  - sealedsecret-postgres.yaml
  - awx.yaml
  - postgres.yaml
