apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: "Homelab"
    theme: dark
    headerStyle: clean
  bookmarks.yaml: |
    - Developer:
    - Github:
        - abbr: GH
          href: https://github.com/

    - Social:
        - Reddit:
            - abbr: RE
              href: https://reddit.com/

    - Entertainment:
        - YouTube:
            - abbr: YT
              href: https://youtube.com/
  services.yaml: |
    # - resources:
    #     cpu: true
    #     memory: true
    #     disk: /
  kubernetes.yaml: |
    mode: cluster
  docker.yaml: |
    host: 127.0.0.1
    # my-docker:
    #   host: 127.0.0.1
    #   port: 2375

    # my-docker:
    #   socket: /var/run/docker.sock
  proxmox.yaml: |
    # url: https://proxmox.host.or.ip:8006
    # token: username@pam!Token ID
    # secret: secret
  custom.css: |
    body {
      --color-primary: #5e81ac;
    }

  custom.js: |
    console.log("Homepage loaded");
  widgets.yaml: |
    - resources:
      cpu: true
      memory: true
      disk: /
    - search:
        provider: duckduckgo
        target: _blank